// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Helixoft.MultiLineSearch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMultiLineSearchPkgString = "29956436-0205-4c9e-9396-abce099383f9";
        public static Guid guidMultiLineSearchPkg = new Guid(guidMultiLineSearchPkgString);

        public const string guidMultiLineSearchCmdSetString = "7d58fc84-2160-4645-be98-eb7f27c358f7";
        public static Guid guidMultiLineSearchCmdSet = new Guid(guidMultiLineSearchCmdSetString);

        public const string guidMainIconString = "8704a9b2-ac3b-4be0-ae4e-c8edb4bd7ef5";
        public static Guid guidMainIcon = new Guid(guidMainIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidMultilineFind = 0x0100;
        public const int bmpMainIco = 0x0001;
    }
}